---
name: After Maven
description: Runs after_maven.sh using xsltproc and count.xslt
branding:
  icon: 'alert-circle'
  color: 'blue'

inputs:
  determine_version:
    description: 'get the version from the main pom.xml, and show that too'
    required: false
    default: 'true'
  coverage:
    description: 'show also coverage from jacoco.xml'
    required: false
    default: 'false'


runs:
  using: "node20"
  main: 'dist/index.js'



