---
name: After Maven
description: Runs after_maven.sh using xsltproc and count.xslt
branding:
  icon: 'alert-circle'
  color: 'blue'

inputs:
  determine_version:
    description: 'get the version from the main pom.xml, and show that too'
    required: false
    default: 'true'
  coverage:
    description: 'show also coverage from jacoco.xml'
    required: false
    default: 'false'
  maven_outcome:
    description: 'outcome of the preceding Maven step; failure makes this action fail'
    required: false
    default: 'success'
  use_simple_class_name:
    description: 'strip package names from reported class name. normally it is clear enough without it'
    required: false
    default: 'true'
  artifactId_pad:
    description: 'pad artifactId to this length'
    required: false
    default: '30'
  name_pad:
    description: 'pad name to this length'
    required: false
    default: '50'


runs:
  using: "node24"
  main: 'dist/index.js'

