= After maven action for github
:toc:

This contains a script that can be run after a maven build.

This script figures out how many tests ran and how many of them failed. The idea is that maven itself can just ignore test failures, and run to its end.


== Usage

Your step to build with maven and report the result might look something like this

[source, yaml]
----
    env:
      MAVEN_ARGS: '--no-transfer-progress'
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Build with Maven
        run: mvn -B -D"maven.test.failure.ignore=true"
      - uses: mmprogrami/after-maven-action@v2
----
Like this, all tests are run (and published). The after-maven-action will then check how many tests ran and how many of them failed, and will fail the action if there were any test failures. The advantage is that in this way all remaining tests are still run, and it is visible what those are. Also there won't be a dip in the coverage if one test happened to fail once.

== Notes about the implementation

This thing will basically  search all failsafe/surefire results xmls and extract the number of tests that ran, failed and errored, and add those up. The results are written in a file 'job.env' which may look something like this:
[source, properties]
----
PROJECT_VERSION=0.19-SNAPSHOT
MAVEN_TESTS_RUN=1626
MAVEN_TESTS_FAILED=8
MAVEN_TESTS_ERROR=7
MAVEN_TESTS_SKIPPED=0
----
If there are failed or errored tests, the action will exit with a code > 0, which will fail the action.

The script is tested for 'ubuntu-latest', 'windows-latest' and 'macos-latest'.

=== TODO 
- Perhaps it is possible to add some parameters, e.g. to optionally fail on test skips, to fail on too few tests run, or to fail on errored tests only, or whatever one may want to do.


=== History

Originally this script was using bash/xsltproc, which made it a bit slow as a github action. So starting from v2 it is purely nodejs.


=== Local development

[source, bash]
----
sudo apt-get install nodejs npm
python3 -m venv ~/venvs/npm
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
nvm install 20

make clean install
----

[source, bash]
----
(main,7)~/github/mihxil/math$ node ~/github/mmprogrami/after-maven-action/dist/index.js
PROJECT_VERSION=0.19-SNAPSHOT
MAVEN_TESTS_RUN=4825
MAVEN_TESTS_FAILED=7
MAVEN_TESTS_ERROR=7
MAVEN_TESTS_SKIPPED=8

mihxil-physics failure: reciprocal org.meeuw.physics.PhysicalNumberTest

mihxil-algebra failure: fromString org.meeuw.test.math.abstractalgebra.complex.ComplexNumberTest
mihxil-algebra failure: times org.meeuw.test.math.abstractalgebra.complex.ComplexNumberTest

mihxil-math-test failure: reciprocal org.meeuw.math.abstractalgebra.reals.RealFieldTest
mihxil-math-test failure: inverse org.meeuw.math.abstractalgebra.reals.RealFieldTest

mihxil-math failure: zeroWithUncertainty org.meeuw.test.math.text.UncertainDoubleFormatTest

mihxil-statistics error: powNegative1 group org.meeuw.math.statistics.StatisticalDoubleTest
mihxil-statistics error: powNegative1 group org.meeuw.math.statistics.StatisticalDoubleTest
mihxil-statistics error: algebraicBinaryOperators org.meeuw.math.statistics.StatisticalDoubleTest
mihxil-statistics error: reciprocal org.meeuw.math.statistics.StatisticalDoubleTest
mihxil-statistics error: division org.meeuw.math.statistics.StatisticalDoubleTest
mihxil-statistics error: algebraicUnaryOperators org.meeuw.math.statistics.StatisticalDoubleTest
mihxil-statistics error: inverse org.meeuw.math.statistics.StatisticalDoubleTest
mihxil-statistics failure: anotherZero org.meeuw.math.statistics.StatisticalDoubleTest

Some (7) tests had errors. Exit 1.
----
